/**
 * ISearchService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.actionmedia.webservice.searchservice;

public interface ISearchService extends java.rmi.Remote {
    public com.actionmedia.webservice.searchservice.SpellTextResponseSpellTextResult spellText(org.apache.axis.types.UnsignedByte pubId, java.lang.String searchString) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SearchSiteResponseSearchSiteResult searchSite(java.lang.String searchString, org.apache.axis.types.UnsignedByte pubId, int[] moduleList, java.lang.Integer pageNumber, java.lang.Integer pageSize, java.lang.Integer snippetSize, java.lang.Integer searchFlag, java.lang.Integer lingvoFlag, int[] searchTagList) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SearchESubscribeResponseSearchESubscribeResult searchESubscribe(java.lang.String searchString, int[] issueIdList, java.lang.Integer pageNumber, java.lang.Integer pageSize, java.lang.Integer searchFlag, java.lang.Integer lingvoFlag, int[] searchTagList) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SearchESubscribeMultiLanguageResponseSearchESubscribeMultiLanguageResult searchESubscribeMultiLanguage(java.lang.String searchString, java.lang.String systemAlias, int[] issueIdList, java.lang.Integer pageNumber, java.lang.Integer pageSize, java.lang.Integer searchFlag, java.lang.Integer lingvoFlag, int[] searchTagList) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SearchLawResponseSearchLawResult searchLaw(java.lang.String searchString, org.apache.axis.types.UnsignedByte pubId, org.apache.axis.types.UnsignedByte pubDivId, int[] excludedModules, int[] searchTagList, org.apache.axis.types.UnsignedByte sortOrder, java.lang.Integer searchOptionFlags, java.lang.Integer snippetSize, java.lang.Integer docPosition, java.lang.Integer pageSize, java.lang.String searchType, org.apache.axis.types.UnsignedByte statusFilter, int[] docRegionIdList, int[] docTypeIdList, int[] docLobbyIdList, int[] docCategoryIdList, java.lang.String docNumber, java.util.Calendar pubDateStartedOn, java.util.Calendar pubDateEndedOn, java.lang.String[] searchPrevStringList, org.apache.axis.types.UnsignedByte moduleIdBacklink, java.lang.Integer idBacklink, java.lang.Integer phraseIdBacklink, java.lang.String userRegionCode, java.lang.Integer pageCount, int[] areaId) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SearchActionDigitalResponseSearchActionDigitalResult searchActionDigital(java.lang.String searchString, org.apache.axis.types.UnsignedByte pubId, org.apache.axis.types.UnsignedByte pubDivId, int[] excludedModules, int[] searchTagList, org.apache.axis.types.UnsignedByte sortOrder, java.lang.Integer searchOptionFlags, java.lang.Integer snippetSize, java.lang.Integer docPosition, java.lang.Integer pageSize, java.lang.String searchType, java.lang.Integer pageCount, int[] areaId) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetSearchSuggestionsResponseGetSearchSuggestionsResult getSearchSuggestions(org.apache.axis.types.UnsignedByte pubId, org.apache.axis.types.UnsignedByte pubDivId, java.lang.String mask) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetPacketSearchSuggestionsResponseGetPacketSearchSuggestionsResult getPacketSearchSuggestions(org.apache.axis.types.UnsignedByte pubId, org.apache.axis.types.UnsignedByte pubDivId, java.lang.String mask, java.lang.Integer packetId) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetSearchHighlightsResponseGetSearchHighlightsResult getSearchHighlights(org.apache.axis.types.UnsignedByte pubID, java.lang.String searchString, org.apache.axis.types.UnsignedByte moduleID, java.lang.Integer documentID) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetSearchHighlightsByPhraseResponseGetSearchHighlightsByPhraseResult getSearchHighlightsByPhrase(org.apache.axis.types.UnsignedByte pubID, java.lang.String searchString, org.apache.axis.types.UnsignedByte moduleID, java.lang.Integer documentID) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetDocumentIndexInfoResponseGetDocumentIndexInfoResult getDocumentIndexInfo(org.apache.axis.types.UnsignedByte pubID, org.apache.axis.types.UnsignedByte moduleID, java.lang.Integer documentID) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetAdvSearchLobbyListResponseGetAdvSearchLobbyListResult getAdvSearchLobbyList(org.apache.axis.types.UnsignedByte pubID, java.lang.String csvTypeIDFilter, java.lang.String csvRegionIDFilter, java.lang.String csvCategoryIDFilter, java.lang.Boolean isActualDocumentOnly, java.lang.Boolean isLucene) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetAdvSearchRegionListResponseGetAdvSearchRegionListResult getAdvSearchRegionList(org.apache.axis.types.UnsignedByte pubID, java.lang.String prefferedRegionCode, java.lang.String csvTypeIDFilter, java.lang.String csvLobbyIDFilter, java.lang.Boolean isActualDocumentOnly, java.lang.Boolean isLucene) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetAdvSearchTypeListResponseGetAdvSearchTypeListResult getAdvSearchTypeList(org.apache.axis.types.UnsignedByte pubID, java.lang.String csvRegionIDFilter, java.lang.String csvLobbyIDFilter, java.lang.String csvCategoryIDFilter, java.lang.Boolean isActualDocumentOnly, java.lang.Boolean isLucene) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetAdvSearchCategoryListResponseGetAdvSearchCategoryListResult getAdvSearchCategoryList(org.apache.axis.types.UnsignedByte pubID, java.lang.String csvTypeIDFilter, java.lang.String csvLobbyIDFilter, java.lang.Boolean isActualDocumentOnly, java.lang.Boolean isLucene) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetAdvSearchSmartNumberListResponseGetAdvSearchSmartNumberListResult getAdvSearchSmartNumberList(org.apache.axis.types.UnsignedByte pubID, java.lang.String pattern, java.lang.Integer listLength, java.lang.Boolean isLucene) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetHightlightInfoResponseGetHightlightInfoResult getHightlightInfo(org.apache.axis.types.UnsignedByte pubId, java.lang.String searchString) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetLingvoInfoResponseGetLingvoInfoResult getLingvoInfo(org.apache.axis.types.UnsignedByte pubId, java.lang.String searchString, java.lang.Integer lingvoFlag) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SearchDocumentResponseSearchDocumentResult searchDocument(java.lang.String searchString) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.ReloadDictionariesResponseReloadDictionariesResult reloadDictionaries() throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetDictionaryInfosResponseGetDictionaryInfosResult getDictionaryInfos() throws java.rmi.RemoteException;
    public void restartService() throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SetSubstitutingServerResponseSetSubstitutingServerResult setSubstitutingServer(java.lang.String substitutingServer) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SetSubstitutingDatabaseResponseSetSubstitutingDatabaseResult setSubstitutingDatabase(java.lang.String originalDatabase, java.lang.String substitutingDatabase) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetSubstitutingEnvironmentResponseGetSubstitutingEnvironmentResult getSubstitutingEnvironment() throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetAdvSearchNumberGroupListResponseGetAdvSearchNumberGroupListResult getAdvSearchNumberGroupList(org.apache.axis.types.UnsignedByte pubId, org.apache.axis.types.UnsignedByte moduleID, java.lang.Integer id, java.lang.Boolean isLucene) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SearchCodeResponseSearchCodeResult searchCode(java.lang.String codeTypeAlias, java.lang.String searchString) throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.GetLogSettingsResponseGetLogSettingsResult getLogSettings() throws java.rmi.RemoteException;
    public com.actionmedia.webservice.searchservice.SetLogSettingsResponseSetLogSettingsResult setLogSettings(java.lang.String logLevel, org.apache.axis.types.UnsignedByte[] pubList) throws java.rmi.RemoteException;
}
