package com.actionmedia.tests.functional.fss.mainpage;

import com.actionmedia.autotest.annotations.TestLink;
import com.actionmedia.base.AbstractDomainTest;
import org.testng.annotations.Test;

import static com.actionmedia.autotest.Group.implemented;
import static com.actionmedia.autotest.Group.smoke;

/**
 * User: n.tyukavkin
 * Date: 12.05.2014
 * Time: 17:53
 */
public class FSS_157_VerifyAccessToDocument extends AbstractDomainTest {

    private static final String AUTH_TEXT_FOR_QUEST = "Материал для подписчиков и в гостевом доступе";
    private static final String AUTH_TEXT_FOR_PAIED_1 = "Документ в платном доступе";
    private static final String AUTH_TEXT_FOR_PAIED_2 = "Получите бесплатный доступ к материалам Системы сроком на 3 дня";
    private static final String ELAPSED_DEMO_TEXT_1 = "Вы уже воспользовались демодоступом.";
    private static final String ELAPSED_DEMO_TEXT_2 = "Как купить доступ";
    private static final String DEMO_TEXT = "Оцените систему с бесплатным пробным доступом на три дня";
    private static final String QUERY_1 = "закон";
    private static final String QUERY_2 = "форма";

    @Test(groups = {smoke, implemented})
    @TestLink(testCaseId = "FSS-157", testCaseVersion = "1")
    public void fss_157_test() {
        report("Пользователь не авторизован");
        enterToFssWithoutLogin()
                .navigateToMainPage()
                .clickSolutionDocumentLink()
                .checkPreviewDocumentIsPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_QUEST)

                .navigateToSolutionsPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkPreviewDocumentIsPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_QUEST)

                .navigateToFormsPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkPreviewDocumentIsPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_QUEST)

                .navigateToDictionaryPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_2)
                .checkTabsOnAuthFormArePresent()
                .checkAuthTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsPresent()
                .clickActivateTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsOpened()
                .checkActivateTabOnAuthFormIsSelected()
                .clickDemoAccessTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsOpened()
                .checkDemoAccessTabOnAuthFormIsSelected()
                .clickAuthTabOnAuthFormIsPresent()
                .checkAuthTabOnAuthFormIsOpened()
                .checkAuthTabOnAuthFormIsSelected()

                .navigateToMagazinesPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .openRandomSoderLink()
                .clickRandomLinkFromSoder()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_2)
                .checkTabsOnAuthFormArePresent()
                .checkAuthTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsPresent()
                .clickActivateTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsOpened()
                .checkActivateTabOnAuthFormIsSelected()
                .clickDemoAccessTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsOpened()
                .checkDemoAccessTabOnAuthFormIsSelected()
                .clickAuthTabOnAuthFormIsPresent()
                .checkAuthTabOnAuthFormIsOpened()
                .checkAuthTabOnAuthFormIsSelected()

                .navigateToVideoPage()
                .clickRandomSectionInRubricator()
                .clickRandomVideoLink()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_2)
                .checkTabsOnAuthFormArePresent()
                .checkAuthTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsPresent()
                .clickActivateTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsOpened()
                .checkActivateTabOnAuthFormIsSelected()
                .clickDemoAccessTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsOpened()
                .checkDemoAccessTabOnAuthFormIsSelected()
                .clickAuthTabOnAuthFormIsPresent()
                .checkAuthTabOnAuthFormIsOpened()
                .checkAuthTabOnAuthFormIsSelected()

                .navigateToSolutionsPage()
                .inputTextInSearchBox(QUERY_1)
                .clickSearchButtonFss()
                .clickRandomDocument()
                .checkPreviewDocumentIsPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_QUEST)

                .navigateToFormsPage()
                .inputTextInSearchBox(QUERY_1)
                .clickSearchButtonFss()
                .clickRandomDocument()
                .checkPreviewDocumentIsPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_QUEST)

                .navigateToDictionaryPage()
                .inputTextInSearchBox(QUERY_1)
                .clickSearchButtonFss()
                .clickRandomDocument()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_2)
                .checkTabsOnAuthFormArePresent()
                .checkAuthTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsPresent()
                .clickActivateTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsOpened()
                .checkActivateTabOnAuthFormIsSelected()
                .clickDemoAccessTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsOpened()
                .checkDemoAccessTabOnAuthFormIsSelected()
                .clickAuthTabOnAuthFormIsPresent()
                .checkAuthTabOnAuthFormIsOpened()
                .checkAuthTabOnAuthFormIsSelected()

                .navigateToMagazinesPage()
                .inputTextInSearchBox(QUERY_1)
                .clickSearchButtonFss()
                .clickRandomDocument()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_2)
                .checkTabsOnAuthFormArePresent()
                .checkAuthTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsPresent()
                .clickActivateTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsOpened()
                .checkActivateTabOnAuthFormIsSelected()
                .clickDemoAccessTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsOpened()
                .checkDemoAccessTabOnAuthFormIsSelected()
                .clickAuthTabOnAuthFormIsPresent()
                .checkAuthTabOnAuthFormIsOpened()
                .checkAuthTabOnAuthFormIsSelected()

                .navigateToVideoPage()
                .inputTextInSearchBox(QUERY_2)
                .clickSearchButtonFss()
                .clickRandomDocument()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_2)
                .checkTabsOnAuthFormArePresent()
                .checkAuthTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsPresent()
                .clickActivateTabOnAuthFormIsPresent()
                .checkActivateTabOnAuthFormIsOpened()
                .checkActivateTabOnAuthFormIsSelected()
                .clickDemoAccessTabOnAuthFormIsPresent()
                .checkDemoAccessTabOnAuthFormIsOpened()
                .checkDemoAccessTabOnAuthFormIsSelected()
                .clickAuthTabOnAuthFormIsPresent()
                .checkAuthTabOnAuthFormIsOpened()
                .checkAuthTabOnAuthFormIsSelected()

                .navigateToLawBasePage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromKodeksRubricator()
                .checkDocumentIsOpened()
                .checkAuthFormIsNotPresent();

        report("Авторизоваться под использованным демодоступом, оплаченного доступа нет.");
        updateLoginAsInfo("fss.user.old.demo");
        loginFss()
                .navigateToSolutionsPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_2)

                .navigateToFormsPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_2)

                .navigateToDictionaryPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_2)

                .navigateToMagazinesPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .openRandomSoderLink()
                .clickRandomLinkFromSoder()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_2)

                .navigateToVideoPage()
                .clickRandomSectionInRubricator()
                .clickRandomVideoLink()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_1)
                .checkAuthFormContainsText(ELAPSED_DEMO_TEXT_2)

                .navigateToLawBasePage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromKodeksRubricator()
                .checkDocumentIsOpened()
                .checkAuthFormIsNotPresent()
                .logout();

        report("Авторизоваться под пользователем с доступом к другим системам (БСС и др.)");
        updateLoginAsInfo("bss.user.commercial");
        loginFss()
                .navigateToSolutionsPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(DEMO_TEXT)

                .navigateToFormsPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(DEMO_TEXT)

                .navigateToDictionaryPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(DEMO_TEXT)

                .navigateToMagazinesPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .openRandomSoderLink()
                .clickRandomLinkFromSoder()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(DEMO_TEXT)

                .navigateToVideoPage()
                .clickRandomSectionInRubricator()
                .clickRandomVideoLink()
                .checkPreviewDocumentIsNotPresent()
                .checkAuthFormIsPresent()
                .checkAuthFormContainsText(AUTH_TEXT_FOR_PAIED_1)
                .checkAuthFormContainsText(DEMO_TEXT)

                .navigateToLawBasePage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromKodeksRubricator()
                .checkDocumentIsOpened()
                .checkAuthFormIsNotPresent()
                .logout();

        report("Авторизоваться под оплаченным доступом.");
        updateLoginAsInfo("fss.user.commercial");
        loginFss()
                .navigateToSolutionsPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkDocumentIsOpened()
                .checkAuthFormIsNotPresent()

                .navigateToFormsPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkDocumentIsOpened()
                .checkAuthFormIsNotPresent()

                .navigateToDictionaryPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromRubricator()
                .checkDocumentIsOpened()
                .checkAuthFormIsNotPresent()

                .navigateToMagazinesPage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .openRandomSoderLink()
                .clickRandomLinkFromSoder()
                .checkDocumentIsOpened()
                .checkAuthFormIsNotPresent()

                .navigateToVideoPage()
                .clickRandomSectionInRubricator()
                .clickRandomVideoLink()
                .checkDocumentIsOpened()
                .checkAuthFormIsNotPresent()

                .navigateToLawBasePage()
                .clickRandomSectionInRubricator()
                .clickRandomSubSectionsInRubricator()
                .clickRandomItemFromKodeksRubricator()
                .checkDocumentIsOpened()
                .checkAuthFormIsNotPresent()
                .logout();
    }
}
